In [2]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('iris_2D_demo.csv', delimiter=',', skip_header=1)
x_data = torch.from_numpy(data[:,0:2])
y_data = torch.from_numpy(data[:,2])

print('X\n', x_data)
print('y\n', y_data)

X
 tensor([[1.4000, 0.2000],
        [1.5000, 0.2000],
        [3.0000, 1.1000],
        [4.1000, 1.3000]], dtype=torch.float64)
y
 tensor([0., 0., 1., 1.], dtype=torch.float64)


In [3]:
# Create a linear layer
linear = nn.Linear(2, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[0.5, -0.1]])
linear.bias.data = torch.Tensor([0.1])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.5000, -0.1000]], requires_grad=True)
Parameter containing:
tensor([0.1000], requires_grad=True)


In [4]:
# some params
loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)
epochs = 1

In [5]:
# training
for epoch in range(epochs):
    for i in range(4):
        x = x_data[i].float()
        y = y_data[i:i+1].float()
        
        # y_hat
        y_hat = torch.sigmoid(linear(x))
        print(f'y_hat: {y_hat.item()}')
        
        # loss        
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')
                    
        # compute gradient
        loss.backward()
        print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')
    
        # update
        optimizer.step()
        optimizer.zero_grad()
        print(f'(b, w): ({linear.bias.data}, {linear.weight.data} \n\n')

y_hat: 0.6856801509857178
loss: 1.1573442220687866
(db, dw): (tensor([0.6857]), tensor([[0.9600, 0.1371]]))
(b, w): (tensor([0.0931]), tensor([[ 0.4904, -0.1014]]) 


y_hat: 0.6917833089828491
loss: 1.1769522428512573
(db, dw): (tensor([0.6918]), tensor([[1.0377, 0.1384]]))
(b, w): (tensor([0.0862]), tensor([[ 0.4800, -0.1028]]) 


y_hat: 0.8042805790901184
loss: 0.2178070843219757
(db, dw): (tensor([-0.1957]), tensor([[-0.5872, -0.2153]]))
(b, w): (tensor([0.0882]), tensor([[ 0.4859, -0.1006]]) 


y_hat: 0.8753998279571533
loss: 0.133074551820755
(db, dw): (tensor([-0.1246]), tensor([[-0.5109, -0.1620]]))
(b, w): (tensor([0.0894]), tensor([[ 0.4910, -0.0990]]) 


