In [2]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('iris_2D_demo.csv', delimiter=',', skip_header=1)
X = torch.from_numpy(data[:,0:2]).float()
y = torch.from_numpy(data[:,2:]).float()

print('X\n', X)
print('y\n', y)

X
 tensor([[1.4000, 0.2000],
        [1.5000, 0.2000],
        [3.0000, 1.1000],
        [4.1000, 1.3000]])
y
 tensor([[0.],
        [0.],
        [1.],
        [1.]])


In [6]:
# Create a linear layer
linear = nn.Linear(2, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[0.5, -0.1]])
linear.bias.data = torch.Tensor([0.1])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.5000, -0.1000]], requires_grad=True)
Parameter containing:
tensor([0.1000], requires_grad=True)


In [3]:
# some params
loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)
epochs = 1

In [4]:
# training
for epoch in range(epochs):        
    # y_hat
    y_hat = torch.sigmoid(linear(X))
    print(f'y_hat: {y_hat}')
    
    # loss        
    loss = loss_fn(y_hat, y)
    print(f'loss: {loss.item()}')
                
    # compute gradient
    loss.backward()
    print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')

    # update
    optimizer.step()
    optimizer.zero_grad()
    print(f'(b, w): ({linear.bias.data}, {linear.weight.data} \n\n')

y_hat: tensor([[0.6857],
        [0.6964],
        [0.8161],
        [0.8829]], grad_fn=<SigmoidBackward0>)
loss: 0.6692625880241394
(db, dw): (tensor([0.2702]), tensor([[ 0.2431, -0.0195]]))
(b, w): (tensor([0.0973]), tensor([[ 0.4976, -0.0998]]) 




In [ ]:
data = np.genfromtxt('iris_2D_demo.csv', 
                     delimiter=',', skip_header=1)
X = torch.from_numpy(data[:,0:2]).float()
y = torch.from_numpy(data[:,2:]).float()

In [ ]:
# Create a linear layer
linear = nn.Linear(2, 1)

# loss and optimizer
loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)

In [ ]:
# training
for epoch in range(epochs):    
    y_hat = torch.sigmoid(linear(X))
    loss = loss_fn(y_hat, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()    