In [1]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:,0:1]).float()
y_data = torch.from_numpy(data[:,1:]).float()

print('X\n', x_data)
print('y\n', y_data)

X
 tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]])
y
 tensor([[9.1000],
        [5.9000],
        [4.6000],
        [6.7000]])


In [2]:
# Create a linear layer
linear = nn.Linear(1, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[-0.34]])
linear.bias.data = torch.Tensor([0.04])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3400]], requires_grad=True)
Parameter containing:
tensor([0.0400], requires_grad=True)


In [3]:
# some params
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)
epochs = 1

In [4]:
# training
for epoch in range(epochs):
    # y_hat
    y_hat = linear(x_data)
    print(f'y_hat: {y_hat}')
    
    # loss        
    loss = loss_fn(y_hat, y_data)
    print(f'loss: {loss}')
                
    # compute gradient
    loss.backward()
    print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')

    # update
    optimizer.step()
    optimizer.zero_grad()
    print(f'(b, w): ({linear.bias.data}, {linear.weight.data}')

y_hat: tensor([[-2.2380],
        [-1.5240],
        [-1.1500],
        [-1.8300]], grad_fn=<AddmmBackward0>)
loss: 72.37236022949219
(db, dw): (tensor([-16.5210]), tensor([[-88.5775]]))
(b, w): (tensor([0.2052]), tensor([[0.5458]])


In [ ]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:, 0:1]).float()
y_data = torch.from_numpy(data[:, 1:]).float()

# Create model, loss and optimizer
linear = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)

# training
epochs = 100
for epoch in range(epochs):
    y_hat = linear(x_data)
    loss = loss_fn(y_hat, y_data)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()    