In [9]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:,0:1])
y_data = torch.from_numpy(data[:,1])

print('X\n', x_data)
print('y\n', y_data)

X
 tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]], dtype=torch.float64)
y
 tensor([9.1000, 5.9000, 4.6000, 6.7000], dtype=torch.float64)


In [13]:
# Create a linear layer
linear = nn.Linear(1, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[-0.34]])
linear.bias.data = torch.Tensor([0.04])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3400]], requires_grad=True)
Parameter containing:
tensor([0.0400], requires_grad=True)


In [14]:
# some params
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)
epochs = 1

In [15]:
# training
for epoch in range(epochs):
    for i in range(4):
        x = x_data[i].float()
        y = y_data[i:i+1].float()
        
        # y_hat
        y_hat = linear(x)
        print(f'y_hat: {y_hat.item()}')
        
        # loss        
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')
                    
        # compute gradient
        loss.backward()
        print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')
    
        # update
        optimizer.step()
        optimizer.zero_grad()
        print(f'(b, w): ({linear.bias.data}, {linear.weight.data} \n\n')

y_hat: -2.23799991607666
loss: 128.5502471923828
(db, dw): (tensor([-22.6760]), tensor([[-151.9292]]))
(b, w): (tensor([0.2668]), tensor([[1.1793]]) 


y_hat: 5.691502571105957
loss: 0.04347121715545654
(db, dw): (tensor([-0.4170]), tensor([[-1.9182]]))
(b, w): (tensor([0.2709]), tensor([[1.1985]]) 


y_hat: 4.465587615966797
loss: 0.018066663295030594
(db, dw): (tensor([-0.2688]), tensor([[-0.9409]]))
(b, w): (tensor([0.2736]), tensor([[1.2079]]) 


y_hat: 6.9169721603393555
loss: 0.0470770001411438
(db, dw): (tensor([0.4339]), tensor([[2.3867]]))
(b, w): (tensor([0.2693]), tensor([[1.1840]]) 


